#ifdef PARAMS_1
  #define CRYPTO_SECRETKEYBYTES 935
  #define CRYPTO_PUBLICKEYBYTES 699
  #define CRYPTO_CIPHERTEXTBYTES 699
  #define CRYPTO_BYTES 32
#endif

#ifdef PARAMS_2
  #define CRYPTO_SECRETKEYBYTES 1234
  #define CRYPTO_PUBLICKEYBYTES 930
  #define CRYPTO_CIPHERTEXTBYTES 930
  #define CRYPTO_BYTES 32
#endif

#ifdef PARAMS_3
  #define CRYPTO_SECRETKEYBYTES 1450
  #define CRYPTO_PUBLICKEYBYTES 1138
  #define CRYPTO_CIPHERTEXTBYTES 1138
  #define CRYPTO_BYTES 32
#endif

#ifdef PARAMS_4
  #define CRYPTO_SECRETKEYBYTES 1590
  #define CRYPTO_PUBLICKEYBYTES 1230
  #define CRYPTO_CIPHERTEXTBYTES 1230
  #define CRYPTO_BYTES 32
#endif
